import { Rubik } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import Navigation from "@/components/Nav";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Learning Next JS",
  description: "Generated by create next app",
};


const handleScroll = (e) => {
  const bottom = e.target.scrollHeight - e.target.scrollTop === e.target.clientHeight;
  if (bottom) console.log("Bottom");
  else console.log("I never reach");
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Provider>
          <div className="bg-background w-screen flex-col flex items-center">
            <Navigation />
            <main>{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
